name: Continuous Integration (CI)

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  pre-commit:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get install cmake libboost-all-dev

      - name: Build project
        run: cmake -S . -B build && cmake --build build

      - name: Run clang-tidy checks
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tidy-checks: ""
