name: Continuous Integration (CI)

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get install cmake libboost-all-dev

      - name: Build project
        run: cmake -S . -B build && cmake --build build
